add rust 1.49.0
meta-rust/meta-rust pull request #293
Opened 2021-02-04 01:35 UTC by danc86

Now it seems `./x.py install` is the only way to assemble a fully
working stage 2 cross-built compiler. See rust-lang/rust#81702.

Fixes #292.

2021-02-04 11:03 UTC, ColinFinck requested changes
I can confirm that your changes finally let the build of the Rust 1.49.0 compiler succeed.
Your solution of patching Rust 1.49.0 for the dash vs. underscore mismatch in the target JSON is even better than my workaround in https://github.com/ColinFinck/meta-rust/commits/update-to-rust-1.49.0

Two points remain though:

"log.do_compile" contains this message now:
```
warning: x.py has made several changes recently you may want to look at
help: consider looking at the changes in `src/bootstrap/CHANGELOG.md`
note: to silence this warning, add `changelog-seen = 2` at the top of `config.toml`
```

Given that you have considered the bootstrap changes, you should add `changelog-seen = 2` to config.toml to prevent this log spam.

---

What still doesn't work for me is building applications with LTO enabled. All our applications use LTO for release builds and this worked well with Rust 1.46.0.
Using your 1.49.0 branch, I'm now getting:

```
error: failed to get bitcode from object file for LTO (Bitcode section not found in object file)
```

2021-02-04 14:04 UTC, ColinFinck commented
Update: I've built with `RUSTC_LOG=debug` and now I know at which file it stops:

```
[1;32m INFO[0m [2mrustc_codegen_llvm::back::lto[0m adding bitcode from std.std.efvtyrxz-cgu.0.rcgu.o
error: failed to get bitcode from object file for LTO (Bitcode section not found in object file)
```

So for some reason, `libstd` is built without a bitcode section and therefore cannot perform LTO. But why??

2021-02-04 23:08 UTC, danc86 commented
Hmmm strange. So this has a good explanation of the bitcode embedding: https://doc.rust-lang.org/rustc/codegen-options/index.html#embed-bitcode
The bootstrap process builds libstd with `-Cembed-bitcode=yes` to allow programs to be linked with or without LTO. We should expect to find an `.llvmbc` section in libstd.rlib.

What I am seeing on my machine is that, for *both* 1.46.0 and the new 1.49.0 recipe, the libstd.rlib for `x86_64-linux` built by the `rust-native` recipe when bootstrapping *does* have the bitcode section, but libstd for my target does not:

```
$ objdump -h tmp-glibc/work/x86_64-linux/rust-native/1.46.0-r0/image/home/danc/work/ngcs/build/tmp-glibc/work/x86_64-linux/rust-native/1.46.0-r0/recipe-sysroot-native/usr/lib/rustlib/x86_64-linux/lib/libstd-528498288d51b68d.rlib | grep llvmbc
  1 .llvmbc       0002627c  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0002b5c4  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00019fc8  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0002d784  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0001bba0  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0001bb70  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00014d90  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00042134  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00030654  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0001f630  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00023214  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       000208e8  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00005374  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0001825c  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       000228d8  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00022e20  0000000000000000  0000000000000000  00000040  2**4
objdump: lib.rmeta: file format not recognized
$ objdump -h tmp-glibc/work/x86_64-linux/rust-native/1.49.0-r0/image/home/danc/work/ngcs/build/tmp-glibc/work/x86_64-linux/rust-native/1.49.0-r0/recipe-sysroot-native/usr/lib/rustlib/x86_64-linux/lib/libstd-0689b0d4825be2a9.rlib  | grep llvmbc
  1 .llvmbc       00024248  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0000a0bc  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00026a14  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00021008  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0002c594  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00021094  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00019cdc  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       000344ec  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0001be94  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0002f0c4  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       00036a14  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0003a694  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0002f304  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       000259e0  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0002fa64  0000000000000000  0000000000000000  00000040  2**4
  1 .llvmbc       0002f1e8  0000000000000000  0000000000000000  00000040  2**4
objdump: lib.rmeta: file format not recognized
$ objdump -h tmp-glibc/work/puma-64-og-linux/libstd-rs/1.46.0-r0/image/usr/lib/rust/libstd.rlib | grep llvmbc
objdump: lib.rmeta: file format not recognized
$ objdump -h tmp-glibc/work/puma-64-og-linux/libstd-rs/1.49.0-r0/image/usr/lib/rust/libstd.rlib | grep llvmbc
objdump: lib.rmeta: file format not recognized
```

That makes me think that our `libstd-rs` recipes need to explicitly request `-Cembed-bitcode=yes` at some point, since that recipe is building libstd outside of the regular bootstrap. Similar to this fix in cargo-xbuild: https://github.com/rust-osdev/cargo-xbuild/pull/73

But it doesn't look like a new problem with these 1.49 recipes. @ColinFinck are you sure you don't have a .bbappend or patch in a local layer for 1.46 which is fixing or workaround this issue somehow?

2021-02-05 00:39 UTC, danc86 commented
Okay I patched the `rust-hello-world` recipe to enable LTO, and I see that it fails to build with:

```
error: failed to get bitcode from object file for LTO (Bitcode section not found in object file)
```

using both these new 1.49 recipes and the latest 1.47 compiler on the master branch. But it builds successfully with the 1.46 compiler. So maybe I made a mistake in my PR for adding 1.47.

2021-02-05 01:19 UTC, danc86 commented
I filed a separate issue #294 for the LTO problems since that affects master, it's nothing specific to this 1.49 PR.

2021-02-05 04:48 UTC, danc86 commented
LTO fix is #295.

Amended this PR to add `changelog-seen = 2`.

2021-02-05 08:43 UTC, ColinFinck requested changes
Thanks a lot for the LTO fix! Merged both of your branches and trying out a build now.

Just had a look at the build log and noticed that:

```
WARNING: cargo-native-1.49.0-r0 do_patch: Fuzz detected:

Applying patch 0001-Disable-http2.patch
patching file Cargo.toml
Hunk #1 succeeded at 25 with fuzz 2.

The context lines in the patches can be updated with devtool:

    devtool modify cargo-native
    devtool finish --force-patch-refresh cargo-native <layer_path>

Don't forget to review changes done by devtool!

WARNING: cargo-native-1.49.0-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]
```

Don't ask me why BitBake is so picky here, but feel free to take my patch from https://github.com/ColinFinck/meta-rust/blob/update-to-rust-1.49.0/recipes-devtools/cargo/cargo-1.49.0/0001-Disable-http2.patch
I also needed several attempts until BitBake was happy.

2021-02-05 21:52 UTC, danc86 commented
Oops, I rebased that patch against 1.48 but forgot to do it again for 1.49.

2021-02-06 00:43 UTC, danc86 commented
I'll update the PR with a rebased patch on Monday. It's already the weekend here in my timezone and my work computer is now disconnected :-)

2021-02-07 22:05 UTC, danc86 commented
Amended to fix patch fuzz on cargo.

I just discovered that our Yocto tree at work is unintentionally disabling all patch fuzz warnings, so now I better go fix that up...

2021-02-08 01:06 UTC, shr-project commented
This isn't specific to 1.49.0 (easily reproducible with 1.47.0 as well), but do you know why target rust and cargo fail to build?

cargo build for aarch64 is showing a lot of:
```
| '+v8' is not a recognized feature for this target (ignoring feature)
```

and sometimes the formatting looks strange as well e.g.
```
| ''+v8' is not a recognized feature for this target (ignoring feature)
| +v8' is not a recognized feature for this target (ignoring feature)
| '+v8' is not a recognized feature for this target (ignoring feature)
| '+v8' is not a recognized feature for this target (ignoring feature)
| '+v8' is not a recognized feature for this target (ignoring feature)
| ''+v8+v8' is not a recognized feature for this target' is not a recognized feature for this target (ignoring feature)
|  (ignoring feature)
| '+v8' is not a recognized feature for this target (ignoring feature)
| '+v8' is not a recognized feature for this target (ignoring feature)
| '+v8' is not a recognized feature for this target (ignoring feature)
| '+v8' is not a recognized feature for this target (ignoring feature)
| ''''''+v8+v8+v8+v8+v8' is not a recognized feature for this target' is not a recognized feature for this target' is not a recognized feature for this target' is not a recognized feature for this target' is not a recognized feature for this target+v8 (ignoring feature)
|  (ignoring feature)
|  (ignoring feature)
|  (ignoring feature)
|  (ignoring feature)
| ' is not a recognized feature for this target (ignoring feature)
| '+v8' is not a recognized feature for this target (ignoring feature)
| '+v8' is not a recognized feature for this target (ignoring feature)
| ''+v8+v8' is not a recognized feature for this target' is not a recognized feature for this target (ignoring feature)
|  (ignoring feature)
```

and it shows it a lot
```
grep -c 'is not a recognized feature for this target (ignoring feature)' cargo/1.49.0-r0/temp/log.do_compile.76960
```

making it more difficult to spot the real error:
```
error[E0463]: can't find crate for `proc_macro`
  --> /usr/src/debug/cargo/1.49.0-r0/rustc-1.49.0-src/vendor/proc-macro2-1.0.19/src/lib.rs:87:1
   |
87 | extern crate proc_macro;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `proc-macro2`
Caused by:
  process didn't exit successfully: `rustc --crate-name proc_macro2 --edition=2018 cargo/1.49.0-r0/rustc-1.49.0-src/vendor/proc-macro2-1.0.19/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=61ec2709a7c9d72c -C extra-filename=-61ec2709a7c9d72c --out-dir cargo/1.49.0-r0/build/target/aarch64-webos-linux/release/deps --target aarch64-webos-linux -C linker=cargo/1.49.0-r0/wrapper/target-rust-ccld -L dependency=cargo/1.49.0-r0/build/target/aarch64-webos-linux/release/deps -L dependency=cargo/1.49.0-r0/build/target/release/deps --extern unicode_xid=cargo/1.49.0-r0/build/target/aarch64-webos-linux/release/deps/libunicode_xid-17f7b0e6b0988b1f.rmeta --cap-lints allow -L cargo/1.49.0-r0/recipe-sysroot/usr/lib/rust --remap-path-prefix=cargo/1.49.0-r0=/usr/src/debug/cargo/1.49.0-r0 --cfg hygiene --cfg use_proc_macro --cfg wrap_proc_macro` (exit code: 1)
```

target rust is failing with just
```
| failed to execute command: "/jenkins/mjansa/build/webos-auto/dunfell/BUILD/work/sa8155-webos-linux/rust/1.49.0-r0/recipe-sysroot/usr/lib/llvm-rust/bin/llvm-config" "--bindir"
| error: No such file or directory (os error 2)
|
|
| Traceback (most recent call last):
|   File "src/bootstrap/bootstrap.py", line 1099, in <module>
|     main()
|   File "src/bootstrap/bootstrap.py", line 1082, in main
|     bootstrap(help_triggered)
|   File "src/bootstrap/bootstrap.py", line 1068, in bootstrap
|     run(args, env=env, verbose=build.verbose)
|   File "src/bootstrap/bootstrap.py", line 153, in run
|     raise RuntimeError(err)
| RuntimeError: failed to run: /jenkins/mjansa/build/webos-auto/dunfell/BUILD/work/sa8155-webos-linux/rust/1.49.0-r0/rustc-1.49.0-src/build/bootstrap/debug/bootstrap -j 90 build --stage 2 --verbose
| WARNING: exit code 1 from a shell command.
|
NOTE: recipe rust-1.49.0-r0: task do_compile: Failed
```

2021-02-08 01:09 UTC, shr-project commented
You should adapt to some of the cleanups which were merged to master today, see https://github.com/meta-rust/meta-rust/pull/300 (and https://github.com/meta-rust/meta-rust/compare/master...shr-project:jansa/lic-1.49.0?expand=1 where I've already rebased your PR on top of that and added the cleanup and RUST_VERSION update for 1.49.0 as well).

2021-02-08 01:33 UTC, jmesmon commented
Right now I'm planning on merging this combined with the cleanups that @shr-project has written (thanks a bunch for running down the issue with the install @danc86).

@shr-project: In general, It would be helpful to me if you'd open a PR for that branch.

We should probably open a separate issue for the "rust for target" issue.

2021-02-08 02:37 UTC, danc86 commented
The README for this layer mentions that rust for target is known not to work, seems to be a long-standing issue: #81

2021-02-08 12:57 UTC, shr-project commented
Fix for "'+v8' is not a recognized feature for this target (ignoring feature)" messages added to #301

2021-02-08 15:09 UTC, jmesmon approved these changes

2021-02-08 15:10 UTC, merged