Bump/rust 1.72
meta-rust/meta-rust pull request #424
Opened 2023-08-25 06:45 UTC by Freax13

2023-08-25 22:56 UTC, tomstokes requested changes
Edit: Nevermind, I got my versions mixed up while reviewing this.

2023-08-25 22:56 UTC, tomstokes commented on recipes-devtools/rust/rust-snapshot-1.72.0.inc
> +SNAPSHOT_VERSION = "1.71.0"
This should be 1.72.0

2023-08-25 22:56 UTC, tomstokes commented on recipes-devtools/rust/rust-snapshot-1.72.0.inc
> +SRC_URI[rust-std-snapshot-x86_64.sha256sum] = "98ae6530c3a41167e9d93d11ea078be98a02f6d809a06d0d51af3ce0f73150d7"
All of these sha256 sums will need to be updated as well once the `SNAPSHOT_VERSION` is correct

2023-08-26 02:59 UTC, srwalter approved these changes

2023-08-26 02:59 UTC, merged