rust: 1.82.0: Fix builds for aarch64 targets
meta-rust/meta-rust pull request #455
Opened 2024-11-12 12:06 UTC by b49020

Rust data layout for aarch64 updated in 1.80.0 release following LLVM data layout update (see: https://github.com/rust-lang/rust/pull/124813).

So conditionally update data layout for aarch64 target build as well.

2024-11-12 12:07 UTC, b49020 commented
@jaskij @srwalter fyi..

2024-11-12 21:58 UTC, jaskij commented
Thanks for catching that. This touches on the deeper parts of the toolchain I'm not familiar with, so no further comment from me.

2024-11-13 03:19 UTC, srwalter commented
Looks like it no build.

2024-11-13 05:54 UTC, b49020 commented
> Looks like it no build.

Strangely it build fine for me locally. I have tried to invert the comparison operation, can you trigger the build again?

2024-12-12 08:32 UTC, albert2004 commented
Issue is also visible on my side (missing Fn32 in DATA_TYPES). Looking at verification result, it looks like yocto syntax is not processed and instead of adding "-Fn32" whole query is added to string.

2024-12-18 17:17 UTC, be-neth commented
Tested on kirkstone, I have failed to build with this PR directly, but another try by replacing double quote by single one in your PR seems to work.

```
DATA_LAYOUT[aarch64] .= "${@'' if bb.utils.vercmp_string_op(d.getVar('RUST_VERSION', True), '1.80.0', '<') else '-Fn32'}"
```

2024-12-18 18:44 UTC, srwalter requested changes

2024-12-18 18:44 UTC, srwalter commented on recipes-devtools/rust/rust-common.inc
> +DATA_LAYOUT[aarch64] .= "${@ "" if bb.utils.vercmp_string_op(d.getVar('RUST_VERSION', True), "1.80.0", "<") else "-Fn32"}"
```suggestion
DATA_LAYOUT[aarch64] .= "${@'' if bb.utils.vercmp_string_op(d.getVar('RUST_VERSION', True), '1.80.0', '<') else '-Fn32'}"
```

2024-12-18 19:25 UTC, be-neth commented
There is something strange with RUST_VERSION definition ?
Builder are complaining that there is no version to strip ?

On my side, with a RUST_VERSION defined somewhere in my layer.conf its working.

2024-12-18 20:08 UTC, srwalter commented on recipes-devtools/rust/rust-common.inc
> +DATA_LAYOUT[aarch64] .= "${@'' if bb.utils.vercmp_string_op(d.getVar('RUST_VERSION', True), '1.80.0', '<') else '-Fn32'}"
```suggestion
DATA_LAYOUT[aarch64] .= "${@'' if bb.utils.vercmp_string_op(d.getVar('PV', True), '1.80.0', '<') else '-Fn32'}"
```

2024-12-18 22:55 UTC, srwalter approved these changes

2024-12-18 22:55 UTC, merged